### ISSUE TITLE
documentation: unclear about how to provide config

### ISSUE THREAD

**Issue by carpeliam** [compozed/deployadactyl#18]
I ended up running `go get github.com/compozed/deployadactyl` and then adding a configuration (as specified in the [Config](https://github.com/compozed/deployadactyl#configuration-file) section) file as `config.yml` in the `~/go/src/github.com/compozed/deployadactyl` directory - I didn't see these steps as documented, but they seemed to work. Does that sound about right?

**Comment by trayo** [comment]
Yes that is correct! Thanks for pointing out the missing information. If you want to add some documentation that is very welcome. Otherwise, we could probably do it later today.

**Comment by carpeliam** [comment]
Thanks @trayo! I'm working as part of a team at @pivotal thinking about using Deployadactyl, which is why we're getting set up with it right now. If it looks like Deployadactyl is a good match for the problem we're working on, we'll probably drift into the pull request route more often than not. If that happens, should we reach out to you guys on slack, or is there a better way of getting in touch?

**Comment by trayo** [comment]
Either one works for us. I've signed up for all notifications on the repo
as well as slack. I don't always get the slack notifications though. If you
want to exchange emails I can send it to you on our slack.
